### ISSUE TITLE
Create API endpoints for Tag APIs

### ISSUE THREAD

**Issue by Thanus-Kumaar** [Naganathan05/Pragati_Backend_2025#32]
## Todo
 - [x] POST add tag
 - [x] GET get all tags
 - [x] DELETE remove a tag
 - [x] PUT edit tag name

### Files to work on:
 - create tagRoute.js
 - create tagController.js
 - create tagModule.js
 - Add necessary validations in dataValidator.js

**Assign yourself and take up the task.**

> [!IMPORTANT] 
> Create a new branch called ```tagAPI``` for working

> [!NOTE]
>   Please try not to create huge pull requests. It will be hard for us to review, commit when necessary and create PRs once every 1 or 2 routes or module functions
