### ISSUE TITLE
Create API endpoints for the club API

### ISSUE THREAD

**Issue by Thanus-Kumaar** [Naganathan05/Pragati_Backend_2025#33]
## Todo

- [x] POST add new club
- [x] GET get all clubs
- [x] PUT edit club details
- [x] DELETE remove club

### Files to work on:
 - create clubRoute.js
 - create clubController.js
 - create clubModule.js
 - Add necessary validations in dataValidator.js

**Assign yourself and take up the task.**

> [!IMPORTANT] 
> Create a new branch called ```clubAPI``` for working

> [!NOTE]
>   Please try not to create huge pull requests. It will be hard for us to review, commit when necessary and create PRs once every 1 or 2 routes or module functions
