### ISSUE TITLE
Create API endpoints for the user API

### ISSUE THREAD

**Issue by Thanus-Kumaar** [Naganathan05/Pragati_Backend_2025#34]
## Todo

- [x] PUT Edit organizer
- [x] DELETE remove organizer
- [x] POST add organizer
- [x] GET get all organizers

### Files to work on:
 - create userRoute.js
 - create userController.js
 - create userModule.js
 - Add necessary validations in dataValidator.js

**Assign yourself and take up the task.**

> [!IMPORTANT] 
> Create a new branch called ```userAPI``` for working

> [!NOTE]
>   Please try not to create huge pull requests. It will be hard for us to review, commit when necessary and create PRs once every 1 or 2 routes or module functions
