### ISSUE TITLE
Create API endpoints for event related APIs

### ISSUE THREAD

**Issue by Thanus-Kumaar** [Naganathan05/Pragati_Backend_2025#36]
## Todo
 - [x] #39
 - [x] GET all events
 - [x] GET events of a specific club.
 - [x] GET individual event
 - [x] PUT edit event
 - [x] #68
 - [x] PUT Toggle Open/Close registration

### Files to work on:
 - create eventRoute.js
 - create eventController.js
 - create eventModule.js
 - Add necessary validations in dataValidator.js

> [!IMPORTANT] 
> Create a new branch called ```teventAPI``` for working

> [!NOTE]
>   Please try not to create huge pull requests. It will be hard for us to review, commit when necessary and create PRs once every 1 or 2 routes or module functions
